config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about-us', to: 'pages#about_us'
  get '/pairing', to: 'pages#pairing'
  get '/tutorial', to: 'pages#tutorial'
  get '/prepwork', to: 'pages#prepwork'
  get '/program-launch', to: 'pages#program_launch'
  get '/prepwork-results', to: 'pages#prepwork_results'
  get '/my-program', to: 'pages#my_program'
  get '/calendar', to: 'pages#calendar'
  get '/daily_program', to: 'pages#daily_program'
  get '/statistics', to: 'pages#statistics'
  get '/trophies', to: 'pages#trophies'
  post '/unlock', to: 'case#unlock'
  get '/add-a-cigarette', to: 'pages#add_a_cigarette'
  get '/manifest.json', to: 'service_worker#manifest'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :smokes, only: [:create, :destroy, :new]
  resources :programs, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :user

  DEMO_DAY = DateTime.new(2020,7,16,10,0,0)

  def prepwork_smokes
    user.smokes.where('created_at < ?', start_time)
  end

  def number_of_days_of_program
    (Date.current - start_time).to_i
  end

  def cigarette_allowed_for(date)
    program_day = get_program_day(date)
    (-average_smoke.fdiv(30) * (program_day + 1) + average_smoke).round
  end

  def average_smoke
    (prepwork_smokes.count / 7).round
  end

  def get_program_day(date)
    (date - start_time).to_i
  end

  def get_next_opening

  end

  def get_spared_cigarettes(date)
    cigarette_allowed_for(date) - smoked_cigarette(date).count
  end

  def get_time_from_last_smoke_to_evening(date)
    #TIME_OF_EVENING - time_of_last_smoke(date)
  end

  def time_of_last_smoke(date)
    user.smokes.where(created_at: date).last.created_at
  end

  def get_spread(date)
    remaining_cigarettes = cigarette_allowed_for(date) - smoked_cigarette(date).count

    if remaining_cigarettes > 0
      ((Time.now.at_end_of_day - 2.hours - user.last_smoke.created_at) / remaining_cigarettes).to_f.round()
    else
      nil
    end
  end

  def smoked_cigarette(date)
    user.smokes.where(created_at: date)
  end

  def get_most_important_smokes(date)
    hours = user.hourly_coefficients
    cigarette_allowed_for = user.program.cigarette_allowed_for(date)
    sorted_by_value_ar_of_ar = hours.sort_by do |key, value|
      -value
    end
    sorted_by_key_ar_of_ar = sorted_by_value_ar_of_ar.first(cigarette_allowed_for).to_h.sort_by do |key, value|
      key
    end
    sorted_by_key_ar_of_ar.to_h
  end

  def get_day_ordanilizer(date)
    if date.day == (1 || 21)
      "st"
    elsif date.day == (2 || 22)
      "nd"
    elsif date.day == (3 || 23)
      "rd"
    else
      "th"
    end
  end
end

app/models/smoke.rb
class Smoke < ApplicationRecord
  belongs_to :user

  scope :today, -> { where(created_at: Date.current.at_beginning_of_day..Date.current.at_end_of_day) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum user_status: {
    created: 'created',
    pairing_done: 'pairing_done',
    in_prepwork: 'in_prepwork',
    ready_to_launch: 'ready_to_launch',
    in_program: 'in_program',
    program_finished: 'program_finished'
  }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :smokes
  has_one :last_smoke, -> { order(created_at: :desc).limit(1) }, class_name: 'Smoke'
  has_one :program

  def get_number_of_smoke(date)
    smokes.where(created_at: date.at_beginning_of_day..date.at_end_of_day).count
  end

  def prepwork_smokes
    self.smokes.where('created_at < ?' , Date.today)
  end

  def get_hours_where_user_smoke
    hours = Hash.new(0)
    self.prepwork_smokes.each do |smoke|
      23.times do |i|
        if smoke.created_at.hour == i
          hours[i] += 1
        end
      end
    end
    return hours
  end

  def hourly_coefficients
    hours = self.get_hours_where_user_smoke
    hours.each do |key, value|
      hours[key] = (value / prepwork_smokes.count.to_f).round(3)
    end
  end

  def average_smoke
    (prepwork_smokes.count / 7).round
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:home, :about_us]

  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :set_layout

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def set_layout
    if params[:controller] == "pages" && %w[statistics calendar daily_program my_profile trophies].include?(params[:action])
      "in_program"
    elsif params[:controller] == "devise/registrations" && params[:action] == "edit"
      "in_program"
    else
      "application"
    end
  end
end

app/controllers/case_controller.rb
require 'net/http'
require 'httparty'

class CaseController < ActionController::Base
  def unlock
    Smoke.create(user:current_user)
    HTTParty.post("#{Case.first.url}/unlock")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      case
      when current_user.user_status == "created"
        redirect_to :pairing
      when current_user.user_status == "pairing_done" || current_user.user_status == "in_prepwork"
        redirect_to :prepwork
      when current_user.user_status == "ready_to_launch"
        redirect_to :prepwork_results
      when current_user.user_status == "in_program"
        redirect_to :daily_program
      else
        render :home
      end
    else
      render :home
    end
  end

  def prepwork
    @smokes = Smoke.where(user_id: current_user.id) # add created add
    render "pages/prepwork"

    # if current_user.created_at > 1 semaine render program is ready
  end

  def daily_program
    @ar_program = current_user.program

    # @program_day = get_program_day(current_user)
    # @program = get_smoking_program(current_user)
    render "pages/daily_program"
  end


  private

  # def get_smoking_program(current_user)
  #   total_smoke = Smoke.where(user: current_user).count
  #   program_date_launch = Program.where(user: current_user).first.start_time
  #   first_smoke_date = Smoke.where(user: current_user).first.created_at.to_datetime
  #   day_of_prepwork = (program_date_launch - first_smoke_date).round
  #   average_smoke = (total_smoke / day_of_prepwork).round
  #   daily_program_smokes = [average_smoke]
  #   30.times do |i|
  #     daily_program_smokes << (-average_smoke.fdiv(30) * (i + 1) + average_smoke).round
  #     i += 1
  #   end
  #   return daily_program_smokes
  # end

  # def get_program_day(current_user)
  #   program_date_launch = Program.where(user: current_user).first.start_time
  #   #current_user.program.start_time
  #   date_of_connexion = Program::DEMO_DAY
  #   program_day = (date_of_connexion - program_date_launch).to_i
  #   return program_day
  # end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def create
    @user = current_user
    @init_smoke = @user.average_smoke
    @start_time = Date.current
    Program.create(user: @user, init_smoke: @init_smoke, start_time: @start_time)
    redirect_to calendar_path(current_user)
  end

  private

  def program_params
    params.require(:program).permit(:user, :init_smoke, :start_time)
  end
end

app/controllers/service_worker_controller.rb
class ServiceWorkerController < ApplicationController
  protect_from_forgery
  skip_before_action :authenticate_user!


  def manifest
  end
end

app/controllers/smokes_controller.rb
class SmokesController < ApplicationController
  def new
  end

  def create
    @user = current_user
    Smoke.create({user: @user})
    redirect_to add_a_cigarette_path
  end

  def destroy
    @smoke = Smoke.last
    @smoke.destroy
    redirect_to add_a_cigarette_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    #raise
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def color_class_for_program(program, value)
    step = (value / (program.max / 9.0)).ceil
    p "max: #{program.max}, value: #{value}, step: #{step}"
    "bg-green-#{step}00"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iBreath</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="manifest" href="/manifest.json">
    <meta property="og:url"         content="https://www.ibreath.io" />
    <meta property="og:title"       content="iBreath : Quit smoking in one month." />
    <meta property="og:image"       content="https://www.loicmalacari.fr/wp-content/uploads/2019/07/stop-Smoking.jpg" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="mobile-web-app-capable"  content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title"  content="iBreath">
    <meta name="apple-mobile-web-app-status-bar-style"  content="black-translucent">
    <link rel="apple-touch-icon" href="<%= image_path 'icons/circlegreen.png' %>" sizes="192x192">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/add_a_cigarette.html.erb
<div class="h-32 bg-indigo-700 w-screen flex flex-row justify-around items-center text-white">
  <%= link_to "Back", daily_program_path, class: "w-12" %>
  <h1 class="leading-tight text-3xl text-center">Add <br>cigarette</h1>
  <p class="w-12"></p>
</div>

<div class="svg-container bg-gray-100" style="padding-bottom: 69px;">
  <div class="datas-a">
    <p><span class="smoked-a"><%= current_user.get_number_of_smoke(Date.current) %></span><span class="text-4xl"> / </span><span class="allowed-a"><%= current_user.program.cigarette_allowed_for(Date.current) %></span></p>
  </div>
  <div class="svg-clope">
  <svg xmlns="http://www.w3.org/2000/svg" width="136.873" height="320.207" viewBox="0 0 136.873 320.207"><defs><style>.a{fill:#474eaf;}</style></defs><g transform="translate(-72.221 -242.887)"><g transform="translate(-24.388 563.094) rotate(-90)"><g transform="translate(0 187.782)"><rect class="a" width="64.227" height="45.699"/></g><g transform="translate(79.766 187.782)"><rect class="a" width="148.136" height="45.699"/></g><g transform="translate(243.44 187.782)"><rect class="a" width="21.754" height="45.699"/></g><g transform="translate(320.207 96.609) rotate(90)"><path class="a" d="M53.695,85.808H23.653a8.115,8.115,0,0,1,0-16.229H55.594a23.135,23.135,0,1,0,0-46.271H23.308a7.778,7.778,0,0,1-7.77-7.769V0H0V15.539A23.334,23.334,0,0,0,23.308,38.847H55.594a7.6,7.6,0,1,1,0,15.193H23.653a23.653,23.653,0,0,0,0,47.307H53.695a9.507,9.507,0,0,1,9.5,9.5v2.244H78.729v-2.244A25.064,25.064,0,0,0,53.695,85.808Z"/></g></g></g></svg>
  </div>
  <div class="button-container">
    <%= link_to smoke_path(Smoke.last), method: "delete" do %>
      <svg id="delete-btn" xmlns="http://www.w3.org/2000/svg" width="74" height="74" viewBox="0 0 74 74"><defs><style>.a{fill:#474eaf;}.b{fill:#4850b2;}</style></defs><path class="a" d="M59.747,10.253A35,35,0,1,0,10.253,59.747,35,35,0,1,0,59.747,10.253ZM56.934,56.934A31.019,31.019,0,0,1,13.066,13.066,31.019,31.019,0,1,1,56.934,56.934Z"/><path class="b" d="M160.356,129.511a1.983,1.983,0,0,0-2.814,0L144.934,142.12l-12.609-12.609a1.989,1.989,0,0,0-2.814,2.814l12.609,12.609-12.609,12.609a2,2,0,0,0,1.4,3.4,1.941,1.941,0,0,0,1.4-.589l12.609-12.609,12.609,12.609a2,2,0,0,0,1.4.589,1.917,1.917,0,0,0,1.4-.589,1.983,1.983,0,0,0,0-2.814l-12.58-12.609,12.609-12.609A1.983,1.983,0,0,0,160.356,129.511Z" transform="translate(-109.934 -109.934)"/></svg>
    <% end %>
    <%= link_to smoke_path, method: "post" do %>
      <svg id="add-btn" xmlns="http://www.w3.org/2000/svg" width="74" height="74" viewBox="0 0 74 74"><defs><style>.a{fill:#474eaf;}</style></defs><path class="a" d="M63.163,10.837A37,37,0,0,0,10.837,63.163,37,37,0,0,0,63.163,10.837ZM37,68.219A31.219,31.219,0,1,1,68.219,37,31.254,31.254,0,0,1,37,68.219Zm2.891-34.112H52.9v5.781H39.891V52.9H34.109V39.888H21.1V34.107H34.109V21.1h5.781Zm0,0"/></svg>
    <% end %>

  </div>
</div>

app/views/pages/daily_program.html.erb
  <div class="flex flex-col justify-center items-center mb-48">
    <h1 class="text-2xl font-bold"> <span class="text-4xl text-indigo-700">Day <%= @ar_program.number_of_days_of_program + 1%></span></h1>
    <p class="my-0 text-center text-xl text-indigo-700 font-bold"><%= Date.current.strftime('%B') %> <%= Date.current.day%><sup><%= @ar_program.get_day_ordanilizer(Date.current)%></sup></p>
  </div>
  <section class="wrapper">
      <section class="dials">
        <div class="dial move bg-gray-100">
          <div class="dial-background one"></div>
          <div class="dial-container container1">
            <div class="wedge"></div>
          </div>
          <div class="dial-container container2">
            <div class="wedge"></div>
          </div>
          <div class="marker start"></div>
          <div class="marker end"></div>
        </div>
        <div class="dial exercise">
          <div class="dial-background two"></div>
          <div class="dial-container container1">
            <div class="wedge"></div>
          </div>
          <div class="marker start"></div>
          <div class="marker end"></div>
        </div>
        <div class="dial stand">
          <div class="dial-background three"></div>
          <div class="dial-container container1">
            <div class="wedge"></div>
          </div>
          <div class="marker start"></div>
          <div class="marker end"></div>
        </div>
        <div class="timer-container bg-gray-100">
          <div class="timer">
            <p>next opening:</p>
            <span> 12:00 </span>
          </div>
        </div>
      </section>
</section>

<% allowed =  current_user.program.cigarette_allowed_for(Date.current) %>
<% smoked = current_user.get_number_of_smoke(Date.current) %>
<%= spared = allowed - smoked%>

<style>
  @keyframes rotate-marker-dial-1 {
/*  // 0%, 6% {
  //   transform: none;
  // }*/
  19%, 100% {
    transform: rotateZ(180deg);
  }
}

@keyframes rotate-bg-dial-1-1 {
/*  // 0%, 0.25% {
  //   transform: rotateZ(0);
  // }*/
  19%, 100% {
    transform: rotateZ(180deg);
  }
}

@keyframes rotate-marker-dial-2 {
/*  // 0%, 6% {
  //   transform: none;
  // }*/
  20%, 100% {
    transform: rotateZ(<%= (smoked * 180).fdiv(allowed) %>deg);
  }
/*  // 91%, 100% {
  //   transform: none;
  // }*/
}

@keyframes rotate-bg-dial-2-1 {
/*  // 0%, 0.5% {
  //   transform: none;
  // }*/
  19%, 100% {
    transform: rotateZ(<%= (smoked * 180).fdiv(allowed) %>deg);
  }
/*  // 91%, 100% {
  //   transform: none;
  // }*/
}

@keyframes rotate-marker-dial-3 {
  19%, 100% {
    transform: rotateZ(<%= (spared * 180).fdiv(allowed).round(2) %>deg);
  }
/*  // 91%, 100% {
  //   transform: none;
  // }*/
}

@keyframes rotate-bg-dial-3-1 {
/*  // 0%, 1% {
  //   transform: none;
  // }*/
  19%, 100% {
    transform: rotateZ(<%= (spared * 180).fdiv(allowed).round(2) %>deg);
  }
/*  // 91%, 100% {
  //   transform: none;
  // }*/
}
</style>


  <div class="z-50 bg-gray-100 w-full rounded-t-md flex flex-col items-center mt-16">
    <div class="bg-gray-100 shadow-md rounded-md flex justify-between items-center h-20 w-10/12 mb-4">
      <p class="text-red-400 text-xl font-bold pl-4 pr-2 leading-6">You <br> smoked</p>
      <div class="bg-red-400 h-full w-7/12 rounded-md flex items-center justify-center pt-2">
        <p class="text-center text-white font-bold leading-5"><strong class="text-5xl">
          <%= current_user.get_number_of_smoke(Date.current) %></strong> <br> cigarettes</p>
      </div>
    </div>
    <div class="bg-indigo-500 shadow-md rounded-md flex justify-between items-center h-20 w-10/12 mb-4">
        <p class="text-white text-xl font-bold pl-4 pr-2 leading-6">You <br> spared</p>
      <div class="bg-gray-100 h-full w-7/12 rounded-md flex items-center justify-center">
        <p class="text-indigo-500 font-bold pl-4 pr-2 leading-5 text-center"> <strong class="text-5xl">
          <%= current_user.program.cigarette_allowed_for(Date.current) - current_user.get_number_of_smoke(Date.current) %> </strong> <br> cigarettes </p>
      </div>
    </div>
    <div class="bg-gray-100 shadow-md rounded-md flex justify-between items-center h-20 w-10/12 mb-4">
      <p class="text-teal-300 text-xl font-bold pl-4 pr-2 leading-6">You can<br> smoke</p>
      <div class="bg-teal-300 h-full w-7/12 rounded-md flex items-center justify-center pt-2">
        <p class="text-center text-white font-bold leading-5"><strong class="text-5xl">
          <%= current_user.program.cigarette_allowed_for(Date.current) %></strong> <br> cigarettes</p>
      </div>
    </div>
    <div class="w-full flex justify-around">
      <div class="bg-gray-100 shadow-md rounded-md">
        <%= link_to unlock_path, method: "post", remote: true do %>
          <svg class="w-16 p-2" fill="none" viewBox="0 0 24 24" stroke="#3F439F">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
          </svg>
        <% end %>
      </div>
      <div class="bg-gray-100 shadow-md rounded-md">
        <%= link_to add_a_cigarette_path do %>
          <svg  class="p-2 pl-3" width="65" height="72.16" viewBox="0 0 67.008 76.16"><defs><style>.a{fill:#4850b2;font-size:45px;font-family:Poppins-Bold, Poppins;font-weight:700;}.b{fill:#474eaf;}</style></defs><g transform="translate(-295.992 -621.84)"><text class="a" transform="translate(329 627)"><tspan x="2.975" y="53">+</tspan></text><g transform="translate(295.992 690.376) rotate(-90)"><g transform="translate(0 19.849)"><rect class="b" width="13.69" height="9.741"/></g><g transform="translate(17.002 19.849)"><rect class="b" width="31.575" height="9.741"/></g><g transform="translate(51.889 19.849)"><rect class="b" width="4.637" height="9.741"/></g><g transform="matrix(0.035, 0.999, -0.999, 0.035, 67.951, 0)"><g transform="translate(0 0)"><path class="b" d="M11.445,18.29h-6.4a1.73,1.73,0,0,1,0-3.459H11.85a4.931,4.931,0,1,0,0-9.862H4.968A1.658,1.658,0,0,1,3.312,3.312V0H0V3.312A4.974,4.974,0,0,0,4.968,8.28H11.85a1.619,1.619,0,1,1,0,3.238H5.042a5.042,5.042,0,1,0,0,10.083h6.4a2.026,2.026,0,0,1,2.024,2.024V24.1h3.312v-.478A5.342,5.342,0,0,0,11.445,18.29Z"/></g></g></g></g></svg>
        <% end %>
      </div>
  </div>

app/views/pages/pairing.html.erb
<!-- successfully -->
<div id="paring" class="container mx-auto bg-gray-100 flex flex-col h-screen overflow-auto items-center">


    <div id=mybtn class="flex-grow w-full flex items-center justify-center">
      <div class="circle bg-teal-400" style="animation-delay: -3s"></div>
      <div class="circle bg-teal-400" style="animation-delay: -2s"></div>
      <div class="circle bg-teal-400" style="animation-delay: -1s"></div>
      <div class="circle bg-teal-400" style="animation-delay: -0s"></div>
      <div class="circle circle-success bg-teal-400 text-white font-bold">
        SUCCESS
      </div>
    </div>

    <p class="text-indigo-700 mb-24 text-center text-3xl">Scan your case</p>

    <%= link_to "Continue", tutorial_path, class:" shadow-md bg-indigo-700 uppercase text-white font-bold mb-20 px-16 py-3 rounded-md" %>

</div>

app/views/pages/shared/_tabbar.html.erb
<div class="z-50 bg-indigo-700 tabbar fixed bottom-0 flex justify-around text-gray-400 pt-2 pb-4 shadow-lg rounded-t-md w-full">
  <%= link_to daily_program_path, class:"w-6 flex items-center flex-col #{'text-white' if params[:action] == 'daily_program'}" do %>
    <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
    </svg>
    <p>Home</p>
  <% end %>

  <%= link_to calendar_path, class:"w-6 flex items-center flex-col #{'text-white' if params[:action] == 'calendar'}" do %>
    <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
    Calendar
    <% end %>

  <%= link_to statistics_path,  class:"w-6 flex items-center flex-col #{'text-white' if params[:action] == 'statistics'}" do %>
    <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
    </svg>
    Stats
  <% end %>

  <%= link_to trophies_path, class:"w-6 flex items-center flex-col #{'text-white' if params[:action] == "trophies"}" do %>
    <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
       viewBox="0 0 595.3 595.3" enable-background="new 0 0 595.3 595.3" xml:space="preserve">
    <g>
      <polygon fill=<%= params[:action] == "trophies" ? "white" : "#cbd5e0" %> stroke="currentColor" stroke-width="4" stroke-miterlimit="10" points="275.7,508 275.7,382.4 299.5,386.3
        323.3,382.4 323.3,508   "/>
      <path fill=<%= params[:action] == "trophies" ? "white" : "#cbd5e0" %> stroke="currentColor" stroke-width="4" stroke-linejoin="round" stroke-miterlimit="10" d="M136.2,79
        c0,0-82.2-41.1-81.9,39.4c0,0-0.8,71.1,45.6,129.4c0,0,36.2,51.4,98.9,71c0,0-17.4-26.8-26.1-47.2c0,0-57-32.4-77.5-99.2
        c0,0-36.2-91.7,40.9-59.1V79H136.2z"/>
      <path fill=<%= params[:action] == "trophies" ? "white" : "#cbd5e0" %> stroke="currentColor" stroke-width="4" stroke-miterlimit="10" d="M299.5,386.3c41.3,0,75.6-37.3,75.6-37.3
        c42.5-42.9,65.7-115.7,65.7-115.7C471.1,154,460,31.4,460,31.4H299.5H138.9c0,0-11,122.6,19.3,201.9c0,0,23.2,72.9,65.7,115.7
        C223.9,349,258.2,386.3,299.5,386.3z"/>
      <path fill=<%= params[:action] == "trophies" ? "white" : "#cbd5e0" %> stroke="currentColor" stroke-width="4" stroke-linejoin="round" stroke-miterlimit="10" d="M463.3,79
        c0,0,82.2-41.1,81.9,39.4c0,0,0.8,71.1-45.6,129.4c0,0-36.2,51.4-98.9,71c0,0,17.4-26.8,26.1-47.2c0,0,57-32.4,77.5-99.2
        c0,0,36.2-91.7-40.9-59.1V79H463.3z"/>
      <rect x="156.5" y="523.4" fill=<%= params[:action] == "trophies" ? "white" : "#cbd5e0" %> stroke="currentColor" stroke-width="4" stroke-miterlimit="10" width="285.9" height="41.6"/>
      <rect x="250.5" y="508" fill=<%= params[:action] == "trophies" ? "white" : "#cbd5e0" %> stroke="currentColor" stroke-width="4" stroke-miterlimit="10" width="98" height="15.4"/>
    </g>
    </svg>
    Trophies
  <% end %>
  <%= link_to edit_user_registration_path, class:"w-6 flex items-center flex-col #{'text-white' if params[:controller] == "devise/registrations" && params[:action] == "edit"}" do %>
    <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
    </svg>
    Profile
  <% end %>
</div>

app/views/programs/create.html.erb
<h1>Programs#create</h1>
<p>Find me in app/views/programs/create.html.erb</p>